---
title: "Intomob123 Heatmaps"
author: "Andres"
date: "21/07/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Libraries

```{r cars}
  library(stringr)
   library(ggplot2)
   library(dplyr)
   library(tidyr)
   library(tibble)
   library(readr)
   library(maps)
   library(glue)
   library("cowplot")
   library("treemapify")
library("Cairo")
library("cairoDevice")
   library(phyloseq)
library("readxl")
library("openxlsx")
library("gplots")
library(forcats)
library(mgcv)
library(phyloseq)
library(vegan)
library(magrittr)
library(tibble)

```
# Open Phyloseq object
```{r}
  ps <- readRDS("intomob123_phyloseq_15March2021_RANKED.rds") 

```  

# Split samples into subsets - Sample types and voyages 

```{r pressure, echo=FALSE}

# Seawater samples
ps_sw <-  ps %>%  
  subset_samples(Sample_Type == "Seawater") %>%
  subset_samples(Water_mass.TS1 != "ANT" ) %>%
  subset_samples((Sampling_Type != "Blank" )) 

```
# Filtration based on Taxonomy - for PROTISTS

```{r pressure, echo=FALSE}

# Protist 
ps_protist <-  ps_sw %>%  
  subset_taxa(!(Division %in% c("Metazoa", "Fungi"))) 

# Protist-synd
ps_protist_synd <- ps_sw %>%
  subset_taxa(!(Division %in% c("Metazoa", "Fungi")))   %>%
     subset_taxa(!(Class %in% c("Syndiniales", "Sarcomonadea")))

# Phyto
ps_phyto <-  ps_sw %>%  
  subset_taxa(!(Division %in% c("Metazoa", "Fungi")))   %>%    
   subset_taxa(Division %in% c("Chlorophyta", "Dinoflagellata", "Cryptophyta", "Haptophyta", "Ochrophyta", "Cercozoa")) %>%
   subset_taxa(!(Class %in% c("Syndiniales", "Sarcomonadea")))

```


# Normalize the otu table 
# Define function - phyloseq_normalize_median

```{r pressure, echo=FALSE}

#PROTIST 
ps_protist_median = median(sample_sums(ps_protist))
normalize_median = function(x, t=ps_protist_median) round(t * (x / sum(x)))
ps_protist_std = transform_sample_counts(ps_protist, normalize_median)

#PROTIST - Syndiniales
ps_protist_synd_median = median(sample_sums(ps_protist_synd))
normalize_median = function(x, t=ps_protist_synd_median) round(t * (x / sum(x)))
ps_protist_synd_std = transform_sample_counts(ps_protist_synd, normalize_median)

```

### SPECIES LEVEL ANALYSIS

# ALL SAmples - SPECIES

```{r, fig.height=15, fig.width=25}

## EUPHOTIC
### Select 50 the most abundant PROTIST-SYND taxa in EUPHOTIC
   ps_protist_synd_std_eu <-  ps_protist_synd_std %>%  
    subset_samples(light_layer == "Euphotic")
  
  topN <- 50
  most_abundant_taxa <- sort(taxa_sums(ps_protist_synd_std_eu), TRUE)[1:topN]
  Euphotic_T50_all <- prune_taxa(names(most_abundant_taxa), ps_protist_synd_std_eu)

## AREA CAST DEPTH - This is Figure 8 that is formatted in illustrator
 
   CairoPDF(file = "R.Figures/Heatmaps/Top50_euphotic_Protist_synd_March2021.pdf", width = 30, height = 10)
  
        plot_heatmap(Euphotic_T50_all, method = "NMDS", distance ="jaccard", binary = TRUE, 
               taxa.label = "Species", taxa.order = "Class", sample.label = "Area_U_Cast_Depth1",
               trans=NULL, low="beige", high="red", na.value="beige") +
              theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust=1, size = 4)) +
              theme(axis.text.y = element_text(size = 12))

  dev.off()
  
# SAMPLE LABEL DEPTH

  CairoPDF(file = "R.Figures/Heatmaps/Top50_euphotic_Protist_synd-March2021.pdf", width = 30, height = 10)
  
        plot_heatmap(Euphotic_T50_all, method = "NMDS", distance ="jaccard", binary = TRUE, 
               taxa.label = "Species", taxa.order = "Class", sample.label = "Sample_label_depth",
               trans=NULL, low="beige", high="red", na.value="beige") +
              theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust=1, size = 4)) +
              theme(axis.text.y = element_text(size = 12))

  dev.off()
  
```

